### ISSUE TITLE
Compiler support

### ISSUE THREAD

**Issue by kzampog** [tomilov/quickhull#5]
Thanks for sharing this code!

I was wondering if it's possible to use your implementation without clang/libc++ (just using gnu stuff).

Thanks!

**Comment by tomilov** [comment]
@kzampog I don't remember what is clang-specific here, but I'll try to port the code to *g++*/*libstdc++* in the evening.

**Comment by Abacn** [comment]
By now the code compiles uses -std=c++14 flag with clang++. It uses std::decay and std::cbegin which is a part of c++14 standard. Even though the compiler outputs warnings such that It uses static_assert with no message info, which is a part of c++17 feature. After some modifications I made it  compile with c++11 standard, because the intel compiler school's computing cluster only supports up to c++11
