### ISSUE TITLE
Out-of-memory issue when nvertices is too big

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [tomilov/quickhull#6]
Hello,

First of all, thank you very much for your library, I find it quick and easy to work with.

I am using it to measure the volume occupied by particles in configurations generated with a [molecular dynamics](https://en.wikipedia.org/wiki/Molecular_dynamics) code. I noticed that, as soon as the number of particles increases above a certain threshold (a few tens of thousands on my machine) the code segfaults. I'm pretty positive that the issue lies with the way the library estimates the maximum number of faces (`unsigned int nfaces = nvertices * (nvertices - 1);`). If nvertices is too big then nfaces can become enormous and the system cannot allocate enough memory, generating issues down the road. 

Since I don't fill skilled enough and my use case is most likely very different from what this library was built for I do not feel comfortable preparing a PR. However, I think that there are ways of mitigating the issue. One would be to check whether malloc returns NULL or not. In the former case, one could either quit with an error or decrease the value of nfaces and issue a warning. There could also be some sort of hard limit for nfaces which could be set with a macro.

**Comment by tomilov** [comment]
Thank you for kind words.
I can suggest to split the task into a smaller ones. It is principally possible due to the volume is additive by nature. I can't quickly suggest how to partition input set of points, but I almost sure it is possible (simple splitting by secant planes for not too uniformly distributed points gives only approximate results (lower estimate), due to voids between).
According to [this theorem](https://de.wikipedia.org/wiki/Eulerscher_Polyedersatz): `nfaces = 2 * (nvertices - 2)` (for triangular faces). Don't think there is quadratic dependence.

**Comment by tomilov** [comment]
Seems you've meant projection to 4D parabaloid. I suggest the following algorithm:
 - First of all find convex hull in 3D.
 - Exclude from further consideration all inner points (for general case of molecular dynamics many of them should be inner).
 - Project resulting points onto 4D parabaloid.
 - Find convex hull of newly created set in 4D.
 - Find 3D measure (volume) for each of 4D-facets (i.e. tetrahedra), then sum them up.
